default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: myapp_development
  host: <%= ENV.fetch('POSTGRES_HOST', 'db') %>  # 使用环境变量，默认为 db

test:
  <<: *default
  database: myapp_test
  host: <%= ENV.fetch('POSTGRES_HOST', 'db') %>  # 使用环境变量，默认为 db

production:
  <<: *default
  database: buddhismrenderdb
  username: saoirseclerks
  password: 2ngrdsajh0GWsWPslIJDcloHE1oi1DBE
  host: dpg-cs6vnhd6l47c738u68ig-a.singapore-postgres.render.com
  port: 5432