name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # 测试工作流
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/test_database

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.7'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Prepare database
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run tests
        run: bundle exec rspec

  # 部署工作流
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.7'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": true}' \
          https://api.render.com/v1/services/srv-cs6ntua3esus73b66br0/deploys

      - name: Run database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bundle exec rails db:migrate

      # 数据导出和导入步骤
      - name: Export local database
        run: pg_dump -U postgres -h db -p 5432 -d myapp_development > backup.sql

      - name: Import data to Render database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: psql -U saoirseclerks -h dpg-cs6vnhd6l47c738u68ig-a.singapore-postgres.render.com -d buddhismrenderdb < backup.sql
